Power board 2022
MST-MRDT/PowerBoardSoftware pull request #4
Opened 2022-02-11 21:19 UTC by dmmm5b

2022-04-25 06:12 UTC, ThisIsBrady requested changes

2022-04-25 06:12 UTC, ThisIsBrady commented on powerboardcode/powerboard/powerboard.h
> +uint8_t bussesMotor[7] = {P_MOTOR1_CTL, P_MOTOR2_CTL, P_MOTOR3_CTL, P_MOTOR4_CTL, P_MOTOR5_CTL, P_MOTOR6_CTL, P_MOTOR7_CTL};
These need to be made consistent with the new manifest

2022-04-25 06:12 UTC, ThisIsBrady commented on powerboardcode/powerboard/powerboard.ino
> +    for (int i = 0 ; i < 8 ; i++)
The upper limits of these for loops (and the rest of them like this) should be made into consts, so you don't have to go through and find all of them any time the manifest changes.

2022-04-28 05:01 UTC, EliVerbrugge commented on powerboardcode/powerboard/powerboard.ino
>      if(packet.data_id != 0)
I think data_id defaults to RC_ROVECOMM_NO_DATA_DATA_ID if nothing was read.

2023-01-13 17:46 UTC, closed without merging